ENHANCERS_ATLAS = getTexture("Enhancers")
BLINDCHIPS_ATLAS = getTexture("BlindChips")
CARD_ATLAS = getTexture("8BitDeck")
JOKER_ATLAS = getTexture("Jokers")
STICKERS_ATLAS = getTexture("Stickers")
CHIPS_ATLAS = getTexture("Chips")
VOUCHERS_ATLAS = getTexture("Vouchers")
BOOSTERS_ATLAS = getTexture("boosters")
